//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_GUITARD_CMD.NS_WS_LOCAL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_BOIS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_BOIS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_BoisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_Bois {
            get {
                return this.Id_BoisField;
            }
            set {
                if ((this.Id_BoisField.Equals(value) != true)) {
                    this.Id_BoisField = value;
                    this.RaisePropertyChanged("Id_Bois");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Prix {
            get {
                return this.PrixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrixField, value) != true)) {
                    this.PrixField = value;
                    this.RaisePropertyChanged("Prix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_MICRO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_MICRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_MicroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_Micro {
            get {
                return this.Id_MicroField;
            }
            set {
                if ((this.Id_MicroField.Equals(value) != true)) {
                    this.Id_MicroField = value;
                    this.RaisePropertyChanged("Id_Micro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Prix {
            get {
                return this.PrixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrixField, value) != true)) {
                    this.PrixField = value;
                    this.RaisePropertyChanged("Prix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_VIBRATO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_VIBRATO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_VibratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_Vibrato {
            get {
                return this.Id_VibratoField;
            }
            set {
                if ((this.Id_VibratoField.Equals(value) != true)) {
                    this.Id_VibratoField = value;
                    this.RaisePropertyChanged("Id_Vibrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Prix {
            get {
                return this.PrixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrixField, value) != true)) {
                    this.PrixField = value;
                    this.RaisePropertyChanged("Prix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_GUITARE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_GUITARE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_GuitareField;
        
        private System.Nullable<int> numeroField;
        
        private int Id_VibratoField;
        
        private int Id_UserField;
        
        private int mancheBoisField;
        
        private int corpsBoisField;
        
        private int toucheBoisField;
        
        private int Id_MicroField;
        
        private int Id_Micro_1Field;
        
        private System.Nullable<int> Id_Micro_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS BoisMancheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS BoisCorpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS BoisToucheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO MicroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO Micro1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO Micro2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_USER ProprietaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO VibratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_Guitare {
            get {
                return this.Id_GuitareField;
            }
            set {
                if ((this.Id_GuitareField.Equals(value) != true)) {
                    this.Id_GuitareField = value;
                    this.RaisePropertyChanged("Id_Guitare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id_Vibrato {
            get {
                return this.Id_VibratoField;
            }
            set {
                if ((this.Id_VibratoField.Equals(value) != true)) {
                    this.Id_VibratoField = value;
                    this.RaisePropertyChanged("Id_Vibrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id_User {
            get {
                return this.Id_UserField;
            }
            set {
                if ((this.Id_UserField.Equals(value) != true)) {
                    this.Id_UserField = value;
                    this.RaisePropertyChanged("Id_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int mancheBois {
            get {
                return this.mancheBoisField;
            }
            set {
                if ((this.mancheBoisField.Equals(value) != true)) {
                    this.mancheBoisField = value;
                    this.RaisePropertyChanged("mancheBois");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int corpsBois {
            get {
                return this.corpsBoisField;
            }
            set {
                if ((this.corpsBoisField.Equals(value) != true)) {
                    this.corpsBoisField = value;
                    this.RaisePropertyChanged("corpsBois");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int toucheBois {
            get {
                return this.toucheBoisField;
            }
            set {
                if ((this.toucheBoisField.Equals(value) != true)) {
                    this.toucheBoisField = value;
                    this.RaisePropertyChanged("toucheBois");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Id_Micro {
            get {
                return this.Id_MicroField;
            }
            set {
                if ((this.Id_MicroField.Equals(value) != true)) {
                    this.Id_MicroField = value;
                    this.RaisePropertyChanged("Id_Micro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Id_Micro_1 {
            get {
                return this.Id_Micro_1Field;
            }
            set {
                if ((this.Id_Micro_1Field.Equals(value) != true)) {
                    this.Id_Micro_1Field = value;
                    this.RaisePropertyChanged("Id_Micro_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> Id_Micro_2 {
            get {
                return this.Id_Micro_2Field;
            }
            set {
                if ((this.Id_Micro_2Field.Equals(value) != true)) {
                    this.Id_Micro_2Field = value;
                    this.RaisePropertyChanged("Id_Micro_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS BoisManche {
            get {
                return this.BoisMancheField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisMancheField, value) != true)) {
                    this.BoisMancheField = value;
                    this.RaisePropertyChanged("BoisManche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS BoisCorps {
            get {
                return this.BoisCorpsField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisCorpsField, value) != true)) {
                    this.BoisCorpsField = value;
                    this.RaisePropertyChanged("BoisCorps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS BoisTouche {
            get {
                return this.BoisToucheField;
            }
            set {
                if ((object.ReferenceEquals(this.BoisToucheField, value) != true)) {
                    this.BoisToucheField = value;
                    this.RaisePropertyChanged("BoisTouche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO Micro {
            get {
                return this.MicroField;
            }
            set {
                if ((object.ReferenceEquals(this.MicroField, value) != true)) {
                    this.MicroField = value;
                    this.RaisePropertyChanged("Micro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO Micro1 {
            get {
                return this.Micro1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro1Field, value) != true)) {
                    this.Micro1Field = value;
                    this.RaisePropertyChanged("Micro1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO Micro2 {
            get {
                return this.Micro2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Micro2Field, value) != true)) {
                    this.Micro2Field = value;
                    this.RaisePropertyChanged("Micro2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_USER Proprietaire {
            get {
                return this.ProprietaireField;
            }
            set {
                if ((object.ReferenceEquals(this.ProprietaireField, value) != true)) {
                    this.ProprietaireField = value;
                    this.RaisePropertyChanged("Proprietaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO Vibrato {
            get {
                return this.VibratoField;
            }
            set {
                if ((object.ReferenceEquals(this.VibratoField, value) != true)) {
                    this.VibratoField = value;
                    this.RaisePropertyChanged("Vibrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_USER", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_USER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telephoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_User {
            get {
                return this.Id_UserField;
            }
            set {
                if ((this.Id_UserField.Equals(value) != true)) {
                    this.Id_UserField = value;
                    this.RaisePropertyChanged("Id_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telephoneField, value) != true)) {
                    this.telephoneField = value;
                    this.RaisePropertyChanged("telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NS_WS_LOCAL.WS_GUITARDSoap")]
    public interface WS_GUITARDSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getBoisResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBois", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponse getBois(WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBois", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponse> getBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément bois1 de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addBois", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponse addBois(WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addBois", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponse> addBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_bois de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setBois", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponse setBois(WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setBois", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponse> setBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getMicrosResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMicros", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponse getMicros(WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMicros", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponse> getMicrosAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément C_micro de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addMicro", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponse addMicro(WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addMicro", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponse> addMicroAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_micro de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setMicro", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponse setMicro(WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setMicro", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponse> setMicroAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getVibratoResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVibrato", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponse getVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponse> getVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément C_vibrato de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addVibrato", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponse addVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addVibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponse> addVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Vibrato de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setVibrato", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponse setVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setVibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponse> setVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getGuitareResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGuitare", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponse getGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGuitare", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponse> getGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément arg1 de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addGuitare", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponse addGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addGuitare", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponse> addGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_guitard de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setGuitare", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponse setGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setGuitare", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponse> setGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_user de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGuitareByUser", ReplyAction="*")]
        WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponse getGuitareByUser(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGuitareByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponse> getGuitareByUserAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBoisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBois", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequestBody Body;
        
        public getBoisRequest() {
        }
        
        public getBoisRequest(WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getBoisRequestBody {
        
        public getBoisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBoisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponseBody Body;
        
        public getBoisResponse() {
        }
        
        public getBoisResponse(WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBoisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS[] getBoisResult;
        
        public getBoisResponseBody() {
        }
        
        public getBoisResponseBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS[] getBoisResult) {
            this.getBoisResult = getBoisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBoisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBois", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequestBody Body;
        
        public addBoisRequest() {
        }
        
        public addBoisRequest(WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addBoisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS bois1;
        
        public addBoisRequestBody() {
        }
        
        public addBoisRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS bois1) {
            this.bois1 = bois1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBoisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponseBody Body;
        
        public addBoisResponse() {
        }
        
        public addBoisResponse(WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addBoisResponseBody {
        
        public addBoisResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setBoisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setBois", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequestBody Body;
        
        public setBoisRequest() {
        }
        
        public setBoisRequest(WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setBoisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS P_bois;
        
        public setBoisRequestBody() {
        }
        
        public setBoisRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS P_bois) {
            this.P_bois = P_bois;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setBoisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setBoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponseBody Body;
        
        public setBoisResponse() {
        }
        
        public setBoisResponse(WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setBoisResponseBody {
        
        public setBoisResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMicrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMicros", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequestBody Body;
        
        public getMicrosRequest() {
        }
        
        public getMicrosRequest(WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getMicrosRequestBody {
        
        public getMicrosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMicrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMicrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponseBody Body;
        
        public getMicrosResponse() {
        }
        
        public getMicrosResponse(WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMicrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO[] getMicrosResult;
        
        public getMicrosResponseBody() {
        }
        
        public getMicrosResponseBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO[] getMicrosResult) {
            this.getMicrosResult = getMicrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addMicroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMicro", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequestBody Body;
        
        public addMicroRequest() {
        }
        
        public addMicroRequest(WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addMicroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO C_micro;
        
        public addMicroRequestBody() {
        }
        
        public addMicroRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO C_micro) {
            this.C_micro = C_micro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addMicroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMicroResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponseBody Body;
        
        public addMicroResponse() {
        }
        
        public addMicroResponse(WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addMicroResponseBody {
        
        public addMicroResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMicroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMicro", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequestBody Body;
        
        public setMicroRequest() {
        }
        
        public setMicroRequest(WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setMicroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO P_micro;
        
        public setMicroRequestBody() {
        }
        
        public setMicroRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO P_micro) {
            this.P_micro = P_micro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMicroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMicroResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponseBody Body;
        
        public setMicroResponse() {
        }
        
        public setMicroResponse(WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setMicroResponseBody {
        
        public setMicroResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVibratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVibrato", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequestBody Body;
        
        public getVibratoRequest() {
        }
        
        public getVibratoRequest(WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getVibratoRequestBody {
        
        public getVibratoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVibratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponseBody Body;
        
        public getVibratoResponse() {
        }
        
        public getVibratoResponse(WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVibratoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO[] getVibratoResult;
        
        public getVibratoResponseBody() {
        }
        
        public getVibratoResponseBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO[] getVibratoResult) {
            this.getVibratoResult = getVibratoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addVibratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addVibrato", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequestBody Body;
        
        public addVibratoRequest() {
        }
        
        public addVibratoRequest(WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addVibratoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO C_vibrato;
        
        public addVibratoRequestBody() {
        }
        
        public addVibratoRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO C_vibrato) {
            this.C_vibrato = C_vibrato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addVibratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addVibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponseBody Body;
        
        public addVibratoResponse() {
        }
        
        public addVibratoResponse(WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addVibratoResponseBody {
        
        public addVibratoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setVibratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setVibrato", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequestBody Body;
        
        public setVibratoRequest() {
        }
        
        public setVibratoRequest(WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setVibratoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO P_Vibrato;
        
        public setVibratoRequestBody() {
        }
        
        public setVibratoRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO P_Vibrato) {
            this.P_Vibrato = P_Vibrato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setVibratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setVibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponseBody Body;
        
        public setVibratoResponse() {
        }
        
        public setVibratoResponse(WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setVibratoResponseBody {
        
        public setVibratoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGuitareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGuitare", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequestBody Body;
        
        public getGuitareRequest() {
        }
        
        public getGuitareRequest(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getGuitareRequestBody {
        
        public getGuitareRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGuitareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGuitareResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponseBody Body;
        
        public getGuitareResponse() {
        }
        
        public getGuitareResponse(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGuitareResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE[] getGuitareResult;
        
        public getGuitareResponseBody() {
        }
        
        public getGuitareResponseBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE[] getGuitareResult) {
            this.getGuitareResult = getGuitareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addGuitareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addGuitare", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequestBody Body;
        
        public addGuitareRequest() {
        }
        
        public addGuitareRequest(WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addGuitareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE arg1;
        
        public addGuitareRequestBody() {
        }
        
        public addGuitareRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE arg1) {
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addGuitareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addGuitareResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponseBody Body;
        
        public addGuitareResponse() {
        }
        
        public addGuitareResponse(WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addGuitareResponseBody {
        
        public addGuitareResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setGuitareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setGuitare", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequestBody Body;
        
        public setGuitareRequest() {
        }
        
        public setGuitareRequest(WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setGuitareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE P_guitard;
        
        public setGuitareRequestBody() {
        }
        
        public setGuitareRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE P_guitard) {
            this.P_guitard = P_guitard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setGuitareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setGuitareResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponseBody Body;
        
        public setGuitareResponse() {
        }
        
        public setGuitareResponse(WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setGuitareResponseBody {
        
        public setGuitareResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGuitareByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGuitareByUser", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequestBody Body;
        
        public getGuitareByUserRequest() {
        }
        
        public getGuitareByUserRequest(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGuitareByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_USER P_user;
        
        public getGuitareByUserRequestBody() {
        }
        
        public getGuitareByUserRequestBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_USER P_user) {
            this.P_user = P_user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGuitareByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGuitareByUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponseBody Body;
        
        public getGuitareByUserResponse() {
        }
        
        public getGuitareByUserResponse(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGuitareByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE[] getGuitareByUserResult;
        
        public getGuitareByUserResponseBody() {
        }
        
        public getGuitareByUserResponseBody(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE[] getGuitareByUserResult) {
            this.getGuitareByUserResult = getGuitareByUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_GUITARDSoapChannel : WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GUITARDSoapClient : System.ServiceModel.ClientBase<WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap>, WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap {
        
        public WS_GUITARDSoapClient() {
        }
        
        public WS_GUITARDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_GUITARDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GUITARDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getBois(WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest request) {
            return base.Channel.getBois(request);
        }
        
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS[] getBois() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequestBody();
            WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getBois(inValue);
            return retVal.Body.getBoisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest request) {
            return base.Channel.getBoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getBoisResponse> getBoisAsync() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getBoisRequestBody();
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getBoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addBois(WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest request) {
            return base.Channel.addBois(request);
        }
        
        public void addBois(WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS bois1) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequestBody();
            inValue.Body.bois1 = bois1;
            WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addBois(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest request) {
            return base.Channel.addBoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addBoisResponse> addBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS bois1) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addBoisRequestBody();
            inValue.Body.bois1 = bois1;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addBoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setBois(WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest request) {
            return base.Channel.setBois(request);
        }
        
        public void setBois(WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS P_bois) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequestBody();
            inValue.Body.P_bois = P_bois;
            WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setBois(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest request) {
            return base.Channel.setBoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setBoisResponse> setBoisAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_BOIS P_bois) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setBoisRequestBody();
            inValue.Body.P_bois = P_bois;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setBoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getMicros(WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest request) {
            return base.Channel.getMicros(request);
        }
        
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO[] getMicros() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequestBody();
            WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getMicros(inValue);
            return retVal.Body.getMicrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getMicrosAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest request) {
            return base.Channel.getMicrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosResponse> getMicrosAsync() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getMicrosRequestBody();
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getMicrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addMicro(WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest request) {
            return base.Channel.addMicro(request);
        }
        
        public void addMicro(WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO C_micro) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequestBody();
            inValue.Body.C_micro = C_micro;
            WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addMicro(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addMicroAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest request) {
            return base.Channel.addMicroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addMicroResponse> addMicroAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO C_micro) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addMicroRequestBody();
            inValue.Body.C_micro = C_micro;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addMicroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setMicro(WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest request) {
            return base.Channel.setMicro(request);
        }
        
        public void setMicro(WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO P_micro) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequestBody();
            inValue.Body.P_micro = P_micro;
            WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setMicro(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setMicroAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest request) {
            return base.Channel.setMicroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setMicroResponse> setMicroAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_MICRO P_micro) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setMicroRequestBody();
            inValue.Body.P_micro = P_micro;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setMicroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest request) {
            return base.Channel.getVibrato(request);
        }
        
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO[] getVibrato() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequestBody();
            WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getVibrato(inValue);
            return retVal.Body.getVibratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest request) {
            return base.Channel.getVibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoResponse> getVibratoAsync() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getVibratoRequestBody();
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getVibratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest request) {
            return base.Channel.addVibrato(request);
        }
        
        public void addVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO C_vibrato) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequestBody();
            inValue.Body.C_vibrato = C_vibrato;
            WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addVibrato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest request) {
            return base.Channel.addVibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoResponse> addVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO C_vibrato) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addVibratoRequestBody();
            inValue.Body.C_vibrato = C_vibrato;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addVibratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest request) {
            return base.Channel.setVibrato(request);
        }
        
        public void setVibrato(WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO P_Vibrato) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequestBody();
            inValue.Body.P_Vibrato = P_Vibrato;
            WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setVibrato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest request) {
            return base.Channel.setVibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoResponse> setVibratoAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_VIBRATO P_Vibrato) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setVibratoRequestBody();
            inValue.Body.P_Vibrato = P_Vibrato;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setVibratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest request) {
            return base.Channel.getGuitare(request);
        }
        
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE[] getGuitare() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequestBody();
            WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getGuitare(inValue);
            return retVal.Body.getGuitareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest request) {
            return base.Channel.getGuitareAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareResponse> getGuitareAsync() {
            WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareRequestBody();
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getGuitareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest request) {
            return base.Channel.addGuitare(request);
        }
        
        public void addGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE arg1) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequestBody();
            inValue.Body.arg1 = arg1;
            WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addGuitare(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.addGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest request) {
            return base.Channel.addGuitareAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareResponse> addGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE arg1) {
            WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.addGuitareRequestBody();
            inValue.Body.arg1 = arg1;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).addGuitareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest request) {
            return base.Channel.setGuitare(request);
        }
        
        public void setGuitare(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE P_guitard) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequestBody();
            inValue.Body.P_guitard = P_guitard;
            WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setGuitare(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.setGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest request) {
            return base.Channel.setGuitareAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareResponse> setGuitareAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE P_guitard) {
            WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.setGuitareRequestBody();
            inValue.Body.P_guitard = P_guitard;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).setGuitareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponse WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getGuitareByUser(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest request) {
            return base.Channel.getGuitareByUser(request);
        }
        
        public WS_GUITARD_CMD.NS_WS_LOCAL.C_GUITARE[] getGuitareByUser(WS_GUITARD_CMD.NS_WS_LOCAL.C_USER P_user) {
            WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequestBody();
            inValue.Body.P_user = P_user;
            WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponse retVal = ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getGuitareByUser(inValue);
            return retVal.Body.getGuitareByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponse> WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap.getGuitareByUserAsync(WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest request) {
            return base.Channel.getGuitareByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserResponse> getGuitareByUserAsync(WS_GUITARD_CMD.NS_WS_LOCAL.C_USER P_user) {
            WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest inValue = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequest();
            inValue.Body = new WS_GUITARD_CMD.NS_WS_LOCAL.getGuitareByUserRequestBody();
            inValue.Body.P_user = P_user;
            return ((WS_GUITARD_CMD.NS_WS_LOCAL.WS_GUITARDSoap)(this)).getGuitareByUserAsync(inValue);
        }
    }
}
