//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_BASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GUITARE
    {
        public int Id_Guitare { get; set; }
        public int Id_Vibrato { get; set; }
        public int Id_User { get; set; }
        public int mancheBois { get; set; }
        public int corpsBois { get; set; }
        public int toucheBois { get; set; }
        public int Id_Micro { get; set; }
        public int Id_Micro_1 { get; set; }
        public Nullable<int> Id_Micro_2 { get; set; }
        public Nullable<int> numero { get; set; }
    
        public virtual C_BOIS BoisManche { get; set; }
        public virtual C_BOIS BoisCorps { get; set; }
        public virtual C_BOIS BoisTouche { get; set; }
        public virtual C_MICRO Micro { get; set; }
        public virtual C_MICRO Micro1 { get; set; }
        public virtual C_MICRO Micro2 { get; set; }
        public virtual C_USER Proprietaire { get; set; }
        public virtual C_VIBRATO Vibrato { get; set; }
    }
}
